nav:
  - Home: 'index.md'
  - HPC for EO: 'units/unit0/README.md'
  - System and infrastructure at JSC: 
    - Plan: 'units/unit1/README.md'
    - User account: 'units/unit1/user-account-setup.md'
    - Virtual environment: 'units/unit1/environment-setup.md'
  - Distributed Deep Learning: 'units/unit2/README.md'
  - Geospatian FMs finetuning: 'units/unit3/README.md'

# Project information
site_name: BIP Course Docs

# Configuration
theme:
  name: material
  palette:
    scheme: bip
  font:
    text: Source Sans 3
    code: DM Mono
  logo: assets/computer.png
  favicon: assets/computer.png
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
