nav:
  - Home: 'index.md'
  - HPC for EO: 'units/unit0/README.md'
  - System and infrastructure at JSC: 'units/unit1/README.md'
  - Distributed Deep Learning: 'units/unit2/README.md'
  - Geospatian FMs finetuning: 'units/unit3/README.md'

# Project information
site_name: BIP Course Docs

# Configuration
theme:
  name: material

# Extensions
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
