[project]
name = "bip-course"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "wandb>=0.19.10",
]

[dependency-groups]
dev = [
    "mkdocs-material>=9.6.12",
]
