[project]
name = "bip-course"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "rasterio>=1.4.3",
    "wandb>=0.19.10",
]

[dependency-groups]
dev = [
    "mkdocs-material>=9.6.12",
]
